-- Electronics category
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('4K Ultra TV #1', 'Smart TV with 4K resolution and HDR. Trade Congress next dark street.', 483.63, 'https://images.pexels.com/photos/704555/pexels-photo-704555.jpeg', 49, 'electronics');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Noise Cancelling Earbuds #2', 'Wireless earbuds with noise cancelling. Must season responsibility your.', 632.29, 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg', 80, 'electronics');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Gaming Laptop #3', 'Laptop with RTX graphics for gaming. Customer career because single.', 1011.54, 'https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg', 24, 'electronics');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Tablet Pro #4', 'Tablet with stylus and 256GB storage. Scene occur prove range happen hold.', 718.86, 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg', 47, 'electronics');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Bluetooth Speaker #5', 'Waterproof speaker with 12h battery. Every organization political you likely course vote cell.', 1204.51, 'https://images.pexels.com/photos/157646/title-photo-logo-thing-157646.jpeg', 57, 'electronics');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Smart Watch #6', 'Fitness tracker with GPS and HR monitor. Sport Congress conference according drive however across.', 894.7, 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg', 95, 'electronics');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Action Camera #7', 'Camera with 4K recording and stabilization. Also company travel act.', 179.91, 'https://images.pexels.com/photos/1787220/pexels-photo-1787220.jpeg', 37, 'electronics');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Drone X #8', 'Quadcopter with HD camera. Later experience situation affect whether cause church.', 1011.48, 'https://images.pexels.com/photos/336232/pexels-photo-336232.jpeg', 89, 'electronics');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('VR Headset #9', 'Virtual reality headset with motion tracking. Seven conference security hope success turn respond.', 739.07, 'https://images.pexels.com/photos/8566472/pexels-photo-8566472.jpeg', 86, 'electronics');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Smartphone Max #10', 'Latest smartphone with AMOLED display. Decision plan watch understand tree traditional.', 102.0, 'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg', 48, 'electronics');

-- Footwear category
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Trail Runner #11', 'Rugged shoes for trail running. Right subject wait look.', 177.85, 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg', 54, 'footwear');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('City Loafers #12', 'Comfort slip-ons for everyday wear. Or dog cut seven officer.', 316.26, 'https://images.pexels.com/photos/267320/pexels-photo-267320.jpeg', 82, 'footwear');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Gym Trainers #13', 'Supportive trainers for indoor workouts. Despite material set.', 259.54, 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg', 83, 'footwear');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Beach Flip Flops #14', 'Light foam flip flops for summer. Wall together follow edge.', 1005.5, 'https://images.pexels.com/photos/1756086/pexels-photo-1756086.jpeg', 40, 'footwear');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Basketball Highs #15', 'High-top sneakers for basketball. Cover address us official hotel.', 59.45, 'https://images.pexels.com/photos/1124465/pexels-photo-1124465.jpeg', 63, 'footwear');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Office Oxfords #16', 'Polished leather shoes for business. Whatever moment sound begin.', 270.53, 'https://images.pexels.com/photos/1464625/pexels-photo-1464625.jpeg', 24, 'footwear');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Boots Classic #17', 'Leather boots for cold weather. Tend indicate knowledge leader thus themselves significant.', 171.77, 'https://images.pexels.com/photos/267242/pexels-photo-267242.jpeg', 75, 'footwear');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Slip-On Casuals #18', 'Easy fit casual shoes. Crime or thought.', 1149.0, 'https://images.pexels.com/photos/1478442/pexels-photo-1478442.jpeg', 70, 'footwear');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Training Shoes #19', 'All-purpose training footwear. Anyone own court statement.', 983.73, 'https://images.pexels.com/photos/1619652/pexels-photo-1619652.jpeg', 56, 'footwear');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Sandals OpenAir #20', 'Breathable sandals for outdoor use. Senior somebody wonder join future away.', 825.26, 'https://images.pexels.com/photos/2562992/pexels-photo-2562992.png', 91, 'footwear');

-- Home category
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('BlenderPro 3000 #21', 'Multi-speed blender for smoothies. Drive occur former future claim help.', 1063.51, 'https://images.pexels.com/photos/760707/pexels-photo-760707.jpeg', 83, 'home');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Auto Kettle #22', 'Electric kettle with auto shut-off. Very miss light nation perform ability teach.', 1282.74, 'https://images.pexels.com/photos/1080532/pexels-photo-1080532.jpeg', 49, 'home');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Air Max Purifier #23', 'Air purifier for allergens and dust. You dog fall nice go past admit campaign.', 1435.08, 'https://images.pexels.com/photos/5824883/pexels-photo-5824883.jpeg', 47, 'home');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('4-Slice Toaster #24', 'Toaster with adjustable browning. Source four five information.', 424.4, 'https://images.pexels.com/photos/175752/pexels-photo-175752.jpeg', 99, 'home');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Compact Microwave #25', '700W microwave for quick meals. Camera cause medical crime mind research the will.', 1467.45, 'https://images.pexels.com/photos/3773435/pexels-photo-3773435.png', 73, 'home');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Smart Light #26', 'Color-changing LED bulb with app control. Choice break tell foot cell option charge.', 1419.98, 'https://images.pexels.com/photos/1166643/pexels-photo-1166643.jpeg', 29, 'home');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Robot Vacuum #27', 'Auto cleaning vacuum with sensors. Support ball treatment line employee political.', 1115.05, 'https://images.pexels.com/photos/4108728/pexels-photo-4108728.jpeg', 27, 'home');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Coffee Brewer #28', 'Drip coffee maker with timer. Market heavy size inside.', 56.07, 'https://images.pexels.com/photos/90915/pexels-photo-90915.jpeg', 78, 'home');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Electric Grill #29', 'Indoor smokeless grill. Some term country mouth base person.', 691.65, 'https://images.pexels.com/photos/2491273/pexels-photo-2491273.jpeg', 37, 'home');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Rice Cooker #30', 'Digital rice cooker with steamer. Large represent allow view spend instead.', 249.35, 'https://images.pexels.com/photos/5908226/pexels-photo-5908226.jpeg', 86, 'home');

-- Accessories category
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Slim Wallet #31', 'Leather wallet with RFID protection. Yourself employee nation baby anyone.', 1486.48, 'https://images.pexels.com/photos/1211974/pexels-photo-1211974.jpeg', 84, 'accessories');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('UV Sunglasses #32', 'Polarized lenses with UV 400. Rest example spend their create.', 1409.2, 'https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg', 56, 'accessories');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Analog Watch #33', 'Stainless steel watch with leather strap. Seem program stuff current.', 1491.46, 'https://images.pexels.com/photos/277390/pexels-photo-277390.jpeg', 25, 'accessories');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Neoprene Sleeve #34', 'Laptop sleeve with zipper. Anyone nor water so condition.', 607.6, 'https://images.pexels.com/photos/5750001/pexels-photo-5750001.jpeg', 39, 'accessories');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Leather Belt #35', 'Adjustable leather belt. Teacher record hundred food attack young.', 1156.24, 'https://images.pexels.com/photos/45055/pexels-photo-45055.jpeg', 49, 'accessories');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Canvas Backpack #36', 'Backpack with laptop section. Point apply plan ago simply itself city notice.', 1416.93, 'https://images.pexels.com/photos/1294731/pexels-photo-1294731.jpeg', 58, 'accessories');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Sports Cap #37', 'Breathable running cap. Could suggest could key experience relate.', 416.19, 'https://images.pexels.com/photos/1124465/pexels-photo-1124465.jpeg', 92, 'accessories');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Travel Pouch #38', 'Organizer for travel essentials. Foot Republican job lead.', 786.18, 'https://images.pexels.com/photos/585418/pexels-photo-585418.jpeg', 40, 'accessories');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Phone Stand #39', 'Foldable stand for smartphones. Personal oil together vote though.', 450.14, 'https://images.pexels.com/photos/1034502/pexels-photo-1034502.jpeg', 31, 'accessories');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Key Organizer #40', 'Compact key holder with clip. Rather agency type home entire song hundred.', 957.72, 'https://images.pexels.com/photos/5620889/pexels-photo-5620889.jpeg', 68, 'accessories');

-- Fitness category
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Dumbbell Pair #41', 'Cast iron dumbbells. Reduce keep book thought approach.', 221.43, 'https://images.pexels.com/photos/1638336/pexels-photo-1638336.jpeg', 39, 'fitness');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Yoga Strap #42', 'Stretching aid for yoga. Have control information degree.', 252.05, 'https://images.pexels.com/photos/8436431/pexels-photo-8436431.jpeg', 55, 'fitness');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Resistance Loops #43', 'Color-coded resistance bands. Response year house call tree little.', 1235.1, 'https://images.pexels.com/photos/6551136/pexels-photo-6551136.jpeg', 78, 'fitness');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Kettlebell Iron #44', 'Solid kettlebell with grip. Trial expert collection eye second war.', 909.17, 'https://images.pexels.com/photos/2204196/pexels-photo-2204196.jpeg', 34, 'fitness');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('RollerPro #45', 'Foam roller for recovery. Research head war window Mr new attack impact.', 538.46, 'https://images.pexels.com/photos/6551094/pexels-photo-6551094.jpeg', 38, 'fitness');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Speed Jump Rope #46', 'Adjustable rope for cardio. Program manager arm memory though.', 907.9, 'https://images.pexels.com/photos/3601094/pexels-photo-3601094.jpeg', 81, 'fitness');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Balance Ball #47', 'Stability ball for workouts. Note social child nature finish lay sell.', 1193.77, 'https://images.pexels.com/photos/5257502/pexels-photo-5257502.jpeg', 65, 'fitness');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Mat Grip #48', 'Non-slip yoga mat. Probably need fact beautiful pull usually.', 1025.35, 'https://images.pexels.com/photos/4498577/pexels-photo-4498577.jpeg', 56, 'fitness');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Push-Up Bars #49', 'Support bars for floor exercises. Program rich consider large blue less.', 458.86, 'https://images.pexels.com/photos/2780762/pexels-photo-2780762.jpeg', 71, 'fitness');
INSERT INTO products (name, description, price, image_url, stock, category) VALUES ('Toning Ring #50', 'Pilates ring for toning. Nothing check present case.', 684.13, 'https://images.pexels.com/photos/8028771/pexels-photo-8028771.jpeg', 49, 'fitness');
